// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (user_id, draw_id, action, repo_owner, repo_name, title)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, draw_id, action, repo_owner, repo_name, title, created_at
`

type CreateActivityParams struct {
	UserID    int64          `json:"user_id"`
	DrawID    pgtype.Int8    `json:"draw_id"`
	Action    ActivityAction `json:"action"`
	RepoOwner pgtype.Text    `json:"repo_owner"`
	RepoName  pgtype.Text    `json:"repo_name"`
	Title     pgtype.Text    `json:"title"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.UserID,
		arg.DrawID,
		arg.Action,
		arg.RepoOwner,
		arg.RepoName,
		arg.Title,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DrawID,
		&i.Action,
		&i.RepoOwner,
		&i.RepoName,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const deleteActivitiesByUserID = `-- name: DeleteActivitiesByUserID :exec
DELETE FROM activities WHERE user_id = $1
`

func (q *Queries) DeleteActivitiesByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteActivitiesByUserID, userID)
	return err
}

const listRecentActivities = `-- name: ListRecentActivities :many
SELECT a.id, a.user_id, a.draw_id, a.action, a.repo_owner, a.repo_name, a.title, a.created_at, u.username, u.avatar_url, u.public_id AS user_public_id
FROM activities a
JOIN users u ON a.user_id = u.id
ORDER BY a.created_at DESC, a.id DESC
LIMIT $1
`

type ListRecentActivitiesRow struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	DrawID       pgtype.Int8        `json:"draw_id"`
	Action       ActivityAction     `json:"action"`
	RepoOwner    pgtype.Text        `json:"repo_owner"`
	RepoName     pgtype.Text        `json:"repo_name"`
	Title        pgtype.Text        `json:"title"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Username     string             `json:"username"`
	AvatarUrl    string             `json:"avatar_url"`
	UserPublicID pgtype.UUID        `json:"user_public_id"`
}

func (q *Queries) ListRecentActivities(ctx context.Context, limit int32) ([]ListRecentActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listRecentActivities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentActivitiesRow{}
	for rows.Next() {
		var i ListRecentActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DrawID,
			&i.Action,
			&i.RepoOwner,
			&i.RepoName,
			&i.Title,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.UserPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivitiesAfterCursor = `-- name: ListRecentActivitiesAfterCursor :many
SELECT a.id, a.user_id, a.draw_id, a.action, a.repo_owner, a.repo_name, a.title, a.created_at, u.username, u.avatar_url, u.public_id AS user_public_id
FROM activities a
JOIN users u ON a.user_id = u.id
WHERE (a.created_at < $1 OR (a.created_at = $1 AND a.id < $3::bigint))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $2
`

type ListRecentActivitiesAfterCursorParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
	CursorID  int64              `json:"cursor_id"`
}

type ListRecentActivitiesAfterCursorRow struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	DrawID       pgtype.Int8        `json:"draw_id"`
	Action       ActivityAction     `json:"action"`
	RepoOwner    pgtype.Text        `json:"repo_owner"`
	RepoName     pgtype.Text        `json:"repo_name"`
	Title        pgtype.Text        `json:"title"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Username     string             `json:"username"`
	AvatarUrl    string             `json:"avatar_url"`
	UserPublicID pgtype.UUID        `json:"user_public_id"`
}

func (q *Queries) ListRecentActivitiesAfterCursor(ctx context.Context, arg ListRecentActivitiesAfterCursorParams) ([]ListRecentActivitiesAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listRecentActivitiesAfterCursor, arg.CreatedAt, arg.Limit, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentActivitiesAfterCursorRow{}
	for rows.Next() {
		var i ListRecentActivitiesAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DrawID,
			&i.Action,
			&i.RepoOwner,
			&i.RepoName,
			&i.Title,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.UserPublicID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
