// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: badges.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const awardBadge = `-- name: AwardBadge :one
INSERT INTO user_badges (user_id, badge_id, draw_id, earned_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, badge_id) DO NOTHING
RETURNING id, user_id, badge_id, draw_id, earned_at
`

type AwardBadgeParams struct {
	UserID  int64       `json:"user_id"`
	BadgeID int64       `json:"badge_id"`
	DrawID  pgtype.Int8 `json:"draw_id"`
}

func (q *Queries) AwardBadge(ctx context.Context, arg AwardBadgeParams) (UserBadge, error) {
	row := q.db.QueryRow(ctx, awardBadge, arg.UserID, arg.BadgeID, arg.DrawID)
	var i UserBadge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BadgeID,
		&i.DrawID,
		&i.EarnedAt,
	)
	return i, err
}

const createBadge = `-- name: CreateBadge :one
INSERT INTO badges (name, description, icon) VALUES ($1, $2, $3)
ON CONFLICT (name) DO NOTHING
RETURNING id, name, description, icon
`

type CreateBadgeParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
}

func (q *Queries) CreateBadge(ctx context.Context, arg CreateBadgeParams) (Badge, error) {
	row := q.db.QueryRow(ctx, createBadge, arg.Name, arg.Description, arg.Icon)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
	)
	return i, err
}

const getBadgeByName = `-- name: GetBadgeByName :one
SELECT id, name, description, icon FROM badges WHERE name = $1
`

func (q *Queries) GetBadgeByName(ctx context.Context, name string) (Badge, error) {
	row := q.db.QueryRow(ctx, getBadgeByName, name)
	var i Badge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
	)
	return i, err
}

const getUserBadgeNames = `-- name: GetUserBadgeNames :many
SELECT b.name FROM user_badges ub JOIN badges b ON ub.badge_id = b.id WHERE ub.user_id = $1
`

func (q *Queries) GetUserBadgeNames(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserBadgeNames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBadges = `-- name: GetUserBadges :many
SELECT ub.earned_at, b.name, b.description, b.icon
FROM user_badges ub
JOIN badges b ON ub.badge_id = b.id
WHERE ub.user_id = $1
ORDER BY ub.earned_at DESC
`

type GetUserBadgesRow struct {
	EarnedAt    pgtype.Timestamptz `json:"earned_at"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Icon        string             `json:"icon"`
}

func (q *Queries) GetUserBadges(ctx context.Context, userID int64) ([]GetUserBadgesRow, error) {
	rows, err := q.db.Query(ctx, getUserBadges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserBadgesRow{}
	for rows.Next() {
		var i GetUserBadgesRow
		if err := rows.Scan(
			&i.EarnedAt,
			&i.Name,
			&i.Description,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBadges = `-- name: ListBadges :many
SELECT id, name, description, icon FROM badges ORDER BY id
`

func (q *Queries) ListBadges(ctx context.Context) ([]Badge, error) {
	rows, err := q.db.Query(ctx, listBadges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Badge{}
	for rows.Next() {
		var i Badge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBadge = `-- name: UpsertBadge :exec
INSERT INTO badges (name, description, icon) VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description, icon = EXCLUDED.icon
`

type UpsertBadgeParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
}

func (q *Queries) UpsertBadge(ctx context.Context, arg UpsertBadgeParams) error {
	_, err := q.db.Exec(ctx, upsertBadge, arg.Name, arg.Description, arg.Icon)
	return err
}
