// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: draws.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bookmarkDraw = `-- name: BookmarkDraw :one
UPDATE draws SET status = 'bookmarked', expires_at = $2 WHERE id = $1 AND status = 'drawn' RETURNING id, public_id, user_id, issue_id, status, source, pr_url, pr_submitted_at, merge_commit_sha, merged_at, expires_at, xp_awarded, created_at, updated_at, pr_owner_login, pr_repo_owner, pr_repo_name, pr_number, pr_verified_at, reward_processed_at, reward_source
`

type BookmarkDrawParams struct {
	ID        int64              `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) BookmarkDraw(ctx context.Context, arg BookmarkDrawParams) (Draw, error) {
	row := q.db.QueryRow(ctx, bookmarkDraw, arg.ID, arg.ExpiresAt)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.IssueID,
		&i.Status,
		&i.Source,
		&i.PrUrl,
		&i.PrSubmittedAt,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ExpiresAt,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrOwnerLogin,
		&i.PrRepoOwner,
		&i.PrRepoName,
		&i.PrNumber,
		&i.PrVerifiedAt,
		&i.RewardProcessedAt,
		&i.RewardSource,
	)
	return i, err
}

const countActiveWorkForUser = `-- name: CountActiveWorkForUser :one
SELECT COUNT(*) FROM draws
WHERE user_id = $1
  AND (
    (status = 'bookmarked' AND (expires_at IS NULL OR expires_at > NOW()))
    OR status = 'pr_submitted'
  )
`

func (q *Queries) CountActiveWorkForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWorkForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDrawsToday = `-- name: CountDrawsToday :one
SELECT COUNT(*) FROM draws
WHERE user_id = $1 AND created_at >= CURRENT_DATE
`

func (q *Queries) CountDrawsToday(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDrawsToday, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMergedDraws = `-- name: CountMergedDraws :one
SELECT COUNT(*) FROM draws WHERE status = 'merged'
`

func (q *Queries) CountMergedDraws(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMergedDraws)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserDraws = `-- name: CountUserDraws :one
SELECT COUNT(*) FROM draws WHERE user_id = $1
`

func (q *Queries) CountUserDraws(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserDraws, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserMergedDraws = `-- name: CountUserMergedDraws :one
SELECT COUNT(*) FROM draws WHERE user_id = $1 AND status = 'merged'
`

func (q *Queries) CountUserMergedDraws(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserMergedDraws, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDraw = `-- name: CreateDraw :one
INSERT INTO draws (user_id, issue_id, status, source)
VALUES ($1, $2, 'drawn', $3)
RETURNING id, public_id, user_id, issue_id, status, source, pr_url, pr_submitted_at, merge_commit_sha, merged_at, expires_at, xp_awarded, created_at, updated_at, pr_owner_login, pr_repo_owner, pr_repo_name, pr_number, pr_verified_at, reward_processed_at, reward_source
`

type CreateDrawParams struct {
	UserID  int64  `json:"user_id"`
	IssueID int64  `json:"issue_id"`
	Source  string `json:"source"`
}

func (q *Queries) CreateDraw(ctx context.Context, arg CreateDrawParams) (Draw, error) {
	row := q.db.QueryRow(ctx, createDraw, arg.UserID, arg.IssueID, arg.Source)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.IssueID,
		&i.Status,
		&i.Source,
		&i.PrUrl,
		&i.PrSubmittedAt,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ExpiresAt,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrOwnerLogin,
		&i.PrRepoOwner,
		&i.PrRepoName,
		&i.PrNumber,
		&i.PrVerifiedAt,
		&i.RewardProcessedAt,
		&i.RewardSource,
	)
	return i, err
}

const getActiveBookmark = `-- name: GetActiveBookmark :one
SELECT id, public_id, user_id, issue_id, status, source, pr_url, pr_submitted_at, merge_commit_sha, merged_at, expires_at, xp_awarded, created_at, updated_at, pr_owner_login, pr_repo_owner, pr_repo_name, pr_number, pr_verified_at, reward_processed_at, reward_source FROM draws
WHERE user_id = $1 AND status = 'bookmarked' AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

func (q *Queries) GetActiveBookmark(ctx context.Context, userID int64) (Draw, error) {
	row := q.db.QueryRow(ctx, getActiveBookmark, userID)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.IssueID,
		&i.Status,
		&i.Source,
		&i.PrUrl,
		&i.PrSubmittedAt,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ExpiresAt,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrOwnerLogin,
		&i.PrRepoOwner,
		&i.PrRepoName,
		&i.PrNumber,
		&i.PrVerifiedAt,
		&i.RewardProcessedAt,
		&i.RewardSource,
	)
	return i, err
}

const getActivePRClaimByIssue = `-- name: GetActivePRClaimByIssue :one
SELECT id, public_id, user_id, issue_id, status, source, pr_url, pr_submitted_at, merge_commit_sha, merged_at, expires_at, xp_awarded, created_at, updated_at, pr_owner_login, pr_repo_owner, pr_repo_name, pr_number, pr_verified_at, reward_processed_at, reward_source FROM draws
WHERE issue_id = $1 AND status = 'pr_submitted' AND user_id <> $2
LIMIT 1
`

type GetActivePRClaimByIssueParams struct {
	IssueID int64 `json:"issue_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) GetActivePRClaimByIssue(ctx context.Context, arg GetActivePRClaimByIssueParams) (Draw, error) {
	row := q.db.QueryRow(ctx, getActivePRClaimByIssue, arg.IssueID, arg.UserID)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.IssueID,
		&i.Status,
		&i.Source,
		&i.PrUrl,
		&i.PrSubmittedAt,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ExpiresAt,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrOwnerLogin,
		&i.PrRepoOwner,
		&i.PrRepoName,
		&i.PrNumber,
		&i.PrVerifiedAt,
		&i.RewardProcessedAt,
		&i.RewardSource,
	)
	return i, err
}

const getDrawByID = `-- name: GetDrawByID :one
SELECT id, public_id, user_id, issue_id, status, source, pr_url, pr_submitted_at, merge_commit_sha, merged_at, expires_at, xp_awarded, created_at, updated_at, pr_owner_login, pr_repo_owner, pr_repo_name, pr_number, pr_verified_at, reward_processed_at, reward_source FROM draws WHERE id = $1
`

func (q *Queries) GetDrawByID(ctx context.Context, id int64) (Draw, error) {
	row := q.db.QueryRow(ctx, getDrawByID, id)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.IssueID,
		&i.Status,
		&i.Source,
		&i.PrUrl,
		&i.PrSubmittedAt,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ExpiresAt,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrOwnerLogin,
		&i.PrRepoOwner,
		&i.PrRepoName,
		&i.PrNumber,
		&i.PrVerifiedAt,
		&i.RewardProcessedAt,
		&i.RewardSource,
	)
	return i, err
}

const getDrawByPRIdentity = `-- name: GetDrawByPRIdentity :one
SELECT id, public_id, user_id, issue_id, status, source, pr_url, pr_submitted_at, merge_commit_sha, merged_at, expires_at, xp_awarded, created_at, updated_at, pr_owner_login, pr_repo_owner, pr_repo_name, pr_number, pr_verified_at, reward_processed_at, reward_source FROM draws
WHERE pr_repo_owner = $1 AND pr_repo_name = $2 AND pr_number = $3 AND status = 'pr_submitted'
`

type GetDrawByPRIdentityParams struct {
	PrRepoOwner pgtype.Text `json:"pr_repo_owner"`
	PrRepoName  pgtype.Text `json:"pr_repo_name"`
	PrNumber    pgtype.Int4 `json:"pr_number"`
}

func (q *Queries) GetDrawByPRIdentity(ctx context.Context, arg GetDrawByPRIdentityParams) (Draw, error) {
	row := q.db.QueryRow(ctx, getDrawByPRIdentity, arg.PrRepoOwner, arg.PrRepoName, arg.PrNumber)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.IssueID,
		&i.Status,
		&i.Source,
		&i.PrUrl,
		&i.PrSubmittedAt,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ExpiresAt,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrOwnerLogin,
		&i.PrRepoOwner,
		&i.PrRepoName,
		&i.PrNumber,
		&i.PrVerifiedAt,
		&i.RewardProcessedAt,
		&i.RewardSource,
	)
	return i, err
}

const getDrawByPRURL = `-- name: GetDrawByPRURL :one
SELECT id, public_id, user_id, issue_id, status, source, pr_url, pr_submitted_at, merge_commit_sha, merged_at, expires_at, xp_awarded, created_at, updated_at, pr_owner_login, pr_repo_owner, pr_repo_name, pr_number, pr_verified_at, reward_processed_at, reward_source FROM draws WHERE pr_url = $1 AND status = 'pr_submitted'
`

func (q *Queries) GetDrawByPRURL(ctx context.Context, prUrl pgtype.Text) (Draw, error) {
	row := q.db.QueryRow(ctx, getDrawByPRURL, prUrl)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.IssueID,
		&i.Status,
		&i.Source,
		&i.PrUrl,
		&i.PrSubmittedAt,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ExpiresAt,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrOwnerLogin,
		&i.PrRepoOwner,
		&i.PrRepoName,
		&i.PrNumber,
		&i.PrVerifiedAt,
		&i.RewardProcessedAt,
		&i.RewardSource,
	)
	return i, err
}

const getDrawByPublicID = `-- name: GetDrawByPublicID :one
SELECT id, public_id, user_id, issue_id, status, source, pr_url, pr_submitted_at, merge_commit_sha, merged_at, expires_at, xp_awarded, created_at, updated_at, pr_owner_login, pr_repo_owner, pr_repo_name, pr_number, pr_verified_at, reward_processed_at, reward_source FROM draws WHERE public_id = $1
`

func (q *Queries) GetDrawByPublicID(ctx context.Context, publicID pgtype.UUID) (Draw, error) {
	row := q.db.QueryRow(ctx, getDrawByPublicID, publicID)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.IssueID,
		&i.Status,
		&i.Source,
		&i.PrUrl,
		&i.PrSubmittedAt,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ExpiresAt,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrOwnerLogin,
		&i.PrRepoOwner,
		&i.PrRepoName,
		&i.PrNumber,
		&i.PrVerifiedAt,
		&i.RewardProcessedAt,
		&i.RewardSource,
	)
	return i, err
}

const getDrawByPublicIDAndUser = `-- name: GetDrawByPublicIDAndUser :one
SELECT id, public_id, user_id, issue_id, status, source, pr_url, pr_submitted_at, merge_commit_sha, merged_at, expires_at, xp_awarded, created_at, updated_at, pr_owner_login, pr_repo_owner, pr_repo_name, pr_number, pr_verified_at, reward_processed_at, reward_source FROM draws WHERE public_id = $1 AND user_id = $2
`

type GetDrawByPublicIDAndUserParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) GetDrawByPublicIDAndUser(ctx context.Context, arg GetDrawByPublicIDAndUserParams) (Draw, error) {
	row := q.db.QueryRow(ctx, getDrawByPublicIDAndUser, arg.PublicID, arg.UserID)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.IssueID,
		&i.Status,
		&i.Source,
		&i.PrUrl,
		&i.PrSubmittedAt,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ExpiresAt,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrOwnerLogin,
		&i.PrRepoOwner,
		&i.PrRepoName,
		&i.PrNumber,
		&i.PrVerifiedAt,
		&i.RewardProcessedAt,
		&i.RewardSource,
	)
	return i, err
}

const getRecentMergedDrawsWithIssues = `-- name: GetRecentMergedDrawsWithIssues :many
SELECT d.id, d.public_id, d.created_at, d.merged_at, d.xp_awarded, i.repo_owner, i.repo_name, i.language, i.labels, i.difficulty
FROM draws d
JOIN issues i ON d.issue_id = i.id
WHERE d.user_id = $1 AND d.status = 'merged'
ORDER BY d.merged_at DESC
LIMIT $2
`

type GetRecentMergedDrawsWithIssuesParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type GetRecentMergedDrawsWithIssuesRow struct {
	ID         int64              `json:"id"`
	PublicID   pgtype.UUID        `json:"public_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	MergedAt   pgtype.Timestamptz `json:"merged_at"`
	XpAwarded  int32              `json:"xp_awarded"`
	RepoOwner  string             `json:"repo_owner"`
	RepoName   string             `json:"repo_name"`
	Language   pgtype.Text        `json:"language"`
	Labels     []string           `json:"labels"`
	Difficulty pgtype.Text        `json:"difficulty"`
}

func (q *Queries) GetRecentMergedDrawsWithIssues(ctx context.Context, arg GetRecentMergedDrawsWithIssuesParams) ([]GetRecentMergedDrawsWithIssuesRow, error) {
	rows, err := q.db.Query(ctx, getRecentMergedDrawsWithIssues, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentMergedDrawsWithIssuesRow{}
	for rows.Next() {
		var i GetRecentMergedDrawsWithIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CreatedAt,
			&i.MergedAt,
			&i.XpAwarded,
			&i.RepoOwner,
			&i.RepoName,
			&i.Language,
			&i.Labels,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDrawStats = `-- name: GetUserDrawStats :one
SELECT
    COUNT(*) AS total_draws,
    COUNT(*) FILTER (WHERE status IN ('bookmarked', 'pr_submitted', 'merged')) AS bookmarked_count,
    COUNT(*) FILTER (WHERE status = 'merged') AS merged_count
FROM draws
WHERE user_id = $1
`

type GetUserDrawStatsRow struct {
	TotalDraws      int64 `json:"total_draws"`
	BookmarkedCount int64 `json:"bookmarked_count"`
	MergedCount     int64 `json:"merged_count"`
}

func (q *Queries) GetUserDrawStats(ctx context.Context, userID int64) (GetUserDrawStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserDrawStats, userID)
	var i GetUserDrawStatsRow
	err := row.Scan(&i.TotalDraws, &i.BookmarkedCount, &i.MergedCount)
	return i, err
}

const getUserHeatmap = `-- name: GetUserHeatmap :many
SELECT DATE(created_at) AS day, COUNT(*) AS count
FROM draws
WHERE user_id = $1 AND created_at >= $2
GROUP BY DATE(created_at)
ORDER BY day
`

type GetUserHeatmapParams struct {
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GetUserHeatmapRow struct {
	Day   pgtype.Date `json:"day"`
	Count int64       `json:"count"`
}

func (q *Queries) GetUserHeatmap(ctx context.Context, arg GetUserHeatmapParams) ([]GetUserHeatmapRow, error) {
	rows, err := q.db.Query(ctx, getUserHeatmap, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserHeatmapRow{}
	for rows.Next() {
		var i GetUserHeatmapRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserMergedDrawsWithIssues = `-- name: GetUserMergedDrawsWithIssues :many
SELECT d.id, d.public_id, d.created_at, d.merged_at, d.xp_awarded, i.repo_owner, i.repo_name, i.language, i.labels, i.difficulty
FROM draws d
JOIN issues i ON d.issue_id = i.id
WHERE d.user_id = $1 AND d.status = 'merged'
ORDER BY d.merged_at DESC
`

type GetUserMergedDrawsWithIssuesRow struct {
	ID         int64              `json:"id"`
	PublicID   pgtype.UUID        `json:"public_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	MergedAt   pgtype.Timestamptz `json:"merged_at"`
	XpAwarded  int32              `json:"xp_awarded"`
	RepoOwner  string             `json:"repo_owner"`
	RepoName   string             `json:"repo_name"`
	Language   pgtype.Text        `json:"language"`
	Labels     []string           `json:"labels"`
	Difficulty pgtype.Text        `json:"difficulty"`
}

func (q *Queries) GetUserMergedDrawsWithIssues(ctx context.Context, userID int64) ([]GetUserMergedDrawsWithIssuesRow, error) {
	rows, err := q.db.Query(ctx, getUserMergedDrawsWithIssues, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserMergedDrawsWithIssuesRow{}
	for rows.Next() {
		var i GetUserMergedDrawsWithIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.CreatedAt,
			&i.MergedAt,
			&i.XpAwarded,
			&i.RepoOwner,
			&i.RepoName,
			&i.Language,
			&i.Labels,
			&i.Difficulty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveWorkForUser = `-- name: ListActiveWorkForUser :many
SELECT d.id, d.public_id, d.user_id, d.issue_id, d.status, d.source, d.pr_url, d.pr_submitted_at, d.merge_commit_sha, d.merged_at, d.expires_at, d.xp_awarded, d.created_at, d.updated_at, d.pr_owner_login, d.pr_repo_owner, d.pr_repo_name, d.pr_number, d.pr_verified_at, d.reward_processed_at, d.reward_source, i.public_id AS issue_public_id, i.repo_owner, i.repo_name, i.title AS issue_title, i.url AS issue_url, i.language AS issue_language, i.difficulty AS issue_difficulty, i.repo_stars AS issue_repo_stars, i.labels AS issue_labels
FROM draws d
JOIN issues i ON d.issue_id = i.id
WHERE d.user_id = $1
  AND (
    (d.status = 'bookmarked' AND (d.expires_at IS NULL OR d.expires_at > NOW()))
    OR d.status = 'pr_submitted'
  )
ORDER BY
  CASE WHEN d.status = 'pr_submitted' THEN 0 ELSE 1 END,
  COALESCE(d.expires_at, '9999-12-31'::timestamptz) ASC,
  d.created_at DESC,
  d.id DESC
`

type ListActiveWorkForUserRow struct {
	ID                int64              `json:"id"`
	PublicID          pgtype.UUID        `json:"public_id"`
	UserID            int64              `json:"user_id"`
	IssueID           int64              `json:"issue_id"`
	Status            DrawStatus         `json:"status"`
	Source            string             `json:"source"`
	PrUrl             pgtype.Text        `json:"pr_url"`
	PrSubmittedAt     pgtype.Timestamptz `json:"pr_submitted_at"`
	MergeCommitSha    pgtype.Text        `json:"merge_commit_sha"`
	MergedAt          pgtype.Timestamptz `json:"merged_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	XpAwarded         int32              `json:"xp_awarded"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PrOwnerLogin      pgtype.Text        `json:"pr_owner_login"`
	PrRepoOwner       pgtype.Text        `json:"pr_repo_owner"`
	PrRepoName        pgtype.Text        `json:"pr_repo_name"`
	PrNumber          pgtype.Int4        `json:"pr_number"`
	PrVerifiedAt      pgtype.Timestamptz `json:"pr_verified_at"`
	RewardProcessedAt pgtype.Timestamptz `json:"reward_processed_at"`
	RewardSource      pgtype.Text        `json:"reward_source"`
	IssuePublicID     pgtype.UUID        `json:"issue_public_id"`
	RepoOwner         string             `json:"repo_owner"`
	RepoName          string             `json:"repo_name"`
	IssueTitle        string             `json:"issue_title"`
	IssueUrl          string             `json:"issue_url"`
	IssueLanguage     pgtype.Text        `json:"issue_language"`
	IssueDifficulty   pgtype.Text        `json:"issue_difficulty"`
	IssueRepoStars    int32              `json:"issue_repo_stars"`
	IssueLabels       []string           `json:"issue_labels"`
}

func (q *Queries) ListActiveWorkForUser(ctx context.Context, userID int64) ([]ListActiveWorkForUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveWorkForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveWorkForUserRow{}
	for rows.Next() {
		var i ListActiveWorkForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.IssueID,
			&i.Status,
			&i.Source,
			&i.PrUrl,
			&i.PrSubmittedAt,
			&i.MergeCommitSha,
			&i.MergedAt,
			&i.ExpiresAt,
			&i.XpAwarded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrOwnerLogin,
			&i.PrRepoOwner,
			&i.PrRepoName,
			&i.PrNumber,
			&i.PrVerifiedAt,
			&i.RewardProcessedAt,
			&i.RewardSource,
			&i.IssuePublicID,
			&i.RepoOwner,
			&i.RepoName,
			&i.IssueTitle,
			&i.IssueUrl,
			&i.IssueLanguage,
			&i.IssueDifficulty,
			&i.IssueRepoStars,
			&i.IssueLabels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDraws = `-- name: ListUserDraws :many
SELECT d.id, d.public_id, d.user_id, d.issue_id, d.status, d.source, d.pr_url, d.pr_submitted_at, d.merge_commit_sha, d.merged_at, d.expires_at, d.xp_awarded, d.created_at, d.updated_at, d.pr_owner_login, d.pr_repo_owner, d.pr_repo_name, d.pr_number, d.pr_verified_at, d.reward_processed_at, d.reward_source, i.public_id AS issue_public_id, i.repo_owner, i.repo_name, i.title AS issue_title, i.url AS issue_url, i.language AS issue_language, i.difficulty AS issue_difficulty, i.repo_stars AS issue_repo_stars, i.labels AS issue_labels
FROM draws d
JOIN issues i ON d.issue_id = i.id
WHERE d.user_id = $1
ORDER BY d.created_at DESC, d.id DESC
LIMIT $2
`

type ListUserDrawsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type ListUserDrawsRow struct {
	ID                int64              `json:"id"`
	PublicID          pgtype.UUID        `json:"public_id"`
	UserID            int64              `json:"user_id"`
	IssueID           int64              `json:"issue_id"`
	Status            DrawStatus         `json:"status"`
	Source            string             `json:"source"`
	PrUrl             pgtype.Text        `json:"pr_url"`
	PrSubmittedAt     pgtype.Timestamptz `json:"pr_submitted_at"`
	MergeCommitSha    pgtype.Text        `json:"merge_commit_sha"`
	MergedAt          pgtype.Timestamptz `json:"merged_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	XpAwarded         int32              `json:"xp_awarded"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PrOwnerLogin      pgtype.Text        `json:"pr_owner_login"`
	PrRepoOwner       pgtype.Text        `json:"pr_repo_owner"`
	PrRepoName        pgtype.Text        `json:"pr_repo_name"`
	PrNumber          pgtype.Int4        `json:"pr_number"`
	PrVerifiedAt      pgtype.Timestamptz `json:"pr_verified_at"`
	RewardProcessedAt pgtype.Timestamptz `json:"reward_processed_at"`
	RewardSource      pgtype.Text        `json:"reward_source"`
	IssuePublicID     pgtype.UUID        `json:"issue_public_id"`
	RepoOwner         string             `json:"repo_owner"`
	RepoName          string             `json:"repo_name"`
	IssueTitle        string             `json:"issue_title"`
	IssueUrl          string             `json:"issue_url"`
	IssueLanguage     pgtype.Text        `json:"issue_language"`
	IssueDifficulty   pgtype.Text        `json:"issue_difficulty"`
	IssueRepoStars    int32              `json:"issue_repo_stars"`
	IssueLabels       []string           `json:"issue_labels"`
}

func (q *Queries) ListUserDraws(ctx context.Context, arg ListUserDrawsParams) ([]ListUserDrawsRow, error) {
	rows, err := q.db.Query(ctx, listUserDraws, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserDrawsRow{}
	for rows.Next() {
		var i ListUserDrawsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.IssueID,
			&i.Status,
			&i.Source,
			&i.PrUrl,
			&i.PrSubmittedAt,
			&i.MergeCommitSha,
			&i.MergedAt,
			&i.ExpiresAt,
			&i.XpAwarded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrOwnerLogin,
			&i.PrRepoOwner,
			&i.PrRepoName,
			&i.PrNumber,
			&i.PrVerifiedAt,
			&i.RewardProcessedAt,
			&i.RewardSource,
			&i.IssuePublicID,
			&i.RepoOwner,
			&i.RepoName,
			&i.IssueTitle,
			&i.IssueUrl,
			&i.IssueLanguage,
			&i.IssueDifficulty,
			&i.IssueRepoStars,
			&i.IssueLabels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDrawsAfterCursor = `-- name: ListUserDrawsAfterCursor :many
SELECT d.id, d.public_id, d.user_id, d.issue_id, d.status, d.source, d.pr_url, d.pr_submitted_at, d.merge_commit_sha, d.merged_at, d.expires_at, d.xp_awarded, d.created_at, d.updated_at, d.pr_owner_login, d.pr_repo_owner, d.pr_repo_name, d.pr_number, d.pr_verified_at, d.reward_processed_at, d.reward_source, i.public_id AS issue_public_id, i.repo_owner, i.repo_name, i.title AS issue_title, i.url AS issue_url, i.language AS issue_language, i.difficulty AS issue_difficulty, i.repo_stars AS issue_repo_stars, i.labels AS issue_labels
FROM draws d
JOIN issues i ON d.issue_id = i.id
WHERE d.user_id = $1 AND (d.created_at < $2 OR (d.created_at = $2 AND d.id < $4::bigint))
ORDER BY d.created_at DESC, d.id DESC
LIMIT $3
`

type ListUserDrawsAfterCursorParams struct {
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
	CursorID  int64              `json:"cursor_id"`
}

type ListUserDrawsAfterCursorRow struct {
	ID                int64              `json:"id"`
	PublicID          pgtype.UUID        `json:"public_id"`
	UserID            int64              `json:"user_id"`
	IssueID           int64              `json:"issue_id"`
	Status            DrawStatus         `json:"status"`
	Source            string             `json:"source"`
	PrUrl             pgtype.Text        `json:"pr_url"`
	PrSubmittedAt     pgtype.Timestamptz `json:"pr_submitted_at"`
	MergeCommitSha    pgtype.Text        `json:"merge_commit_sha"`
	MergedAt          pgtype.Timestamptz `json:"merged_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	XpAwarded         int32              `json:"xp_awarded"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PrOwnerLogin      pgtype.Text        `json:"pr_owner_login"`
	PrRepoOwner       pgtype.Text        `json:"pr_repo_owner"`
	PrRepoName        pgtype.Text        `json:"pr_repo_name"`
	PrNumber          pgtype.Int4        `json:"pr_number"`
	PrVerifiedAt      pgtype.Timestamptz `json:"pr_verified_at"`
	RewardProcessedAt pgtype.Timestamptz `json:"reward_processed_at"`
	RewardSource      pgtype.Text        `json:"reward_source"`
	IssuePublicID     pgtype.UUID        `json:"issue_public_id"`
	RepoOwner         string             `json:"repo_owner"`
	RepoName          string             `json:"repo_name"`
	IssueTitle        string             `json:"issue_title"`
	IssueUrl          string             `json:"issue_url"`
	IssueLanguage     pgtype.Text        `json:"issue_language"`
	IssueDifficulty   pgtype.Text        `json:"issue_difficulty"`
	IssueRepoStars    int32              `json:"issue_repo_stars"`
	IssueLabels       []string           `json:"issue_labels"`
}

func (q *Queries) ListUserDrawsAfterCursor(ctx context.Context, arg ListUserDrawsAfterCursorParams) ([]ListUserDrawsAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listUserDrawsAfterCursor,
		arg.UserID,
		arg.CreatedAt,
		arg.Limit,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserDrawsAfterCursorRow{}
	for rows.Next() {
		var i ListUserDrawsAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.IssueID,
			&i.Status,
			&i.Source,
			&i.PrUrl,
			&i.PrSubmittedAt,
			&i.MergeCommitSha,
			&i.MergedAt,
			&i.ExpiresAt,
			&i.XpAwarded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrOwnerLogin,
			&i.PrRepoOwner,
			&i.PrRepoName,
			&i.PrNumber,
			&i.PrVerifiedAt,
			&i.RewardProcessedAt,
			&i.RewardSource,
			&i.IssuePublicID,
			&i.RepoOwner,
			&i.RepoName,
			&i.IssueTitle,
			&i.IssueUrl,
			&i.IssueLanguage,
			&i.IssueDifficulty,
			&i.IssueRepoStars,
			&i.IssueLabels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDrawsByStatus = `-- name: ListUserDrawsByStatus :many
SELECT d.id, d.public_id, d.user_id, d.issue_id, d.status, d.source, d.pr_url, d.pr_submitted_at, d.merge_commit_sha, d.merged_at, d.expires_at, d.xp_awarded, d.created_at, d.updated_at, d.pr_owner_login, d.pr_repo_owner, d.pr_repo_name, d.pr_number, d.pr_verified_at, d.reward_processed_at, d.reward_source, i.public_id AS issue_public_id, i.repo_owner, i.repo_name, i.title AS issue_title, i.url AS issue_url, i.language AS issue_language, i.difficulty AS issue_difficulty, i.repo_stars AS issue_repo_stars, i.labels AS issue_labels
FROM draws d
JOIN issues i ON d.issue_id = i.id
WHERE d.user_id = $1 AND d.status = $2
ORDER BY d.created_at DESC, d.id DESC
LIMIT $3
`

type ListUserDrawsByStatusParams struct {
	UserID int64      `json:"user_id"`
	Status DrawStatus `json:"status"`
	Limit  int32      `json:"limit"`
}

type ListUserDrawsByStatusRow struct {
	ID                int64              `json:"id"`
	PublicID          pgtype.UUID        `json:"public_id"`
	UserID            int64              `json:"user_id"`
	IssueID           int64              `json:"issue_id"`
	Status            DrawStatus         `json:"status"`
	Source            string             `json:"source"`
	PrUrl             pgtype.Text        `json:"pr_url"`
	PrSubmittedAt     pgtype.Timestamptz `json:"pr_submitted_at"`
	MergeCommitSha    pgtype.Text        `json:"merge_commit_sha"`
	MergedAt          pgtype.Timestamptz `json:"merged_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	XpAwarded         int32              `json:"xp_awarded"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PrOwnerLogin      pgtype.Text        `json:"pr_owner_login"`
	PrRepoOwner       pgtype.Text        `json:"pr_repo_owner"`
	PrRepoName        pgtype.Text        `json:"pr_repo_name"`
	PrNumber          pgtype.Int4        `json:"pr_number"`
	PrVerifiedAt      pgtype.Timestamptz `json:"pr_verified_at"`
	RewardProcessedAt pgtype.Timestamptz `json:"reward_processed_at"`
	RewardSource      pgtype.Text        `json:"reward_source"`
	IssuePublicID     pgtype.UUID        `json:"issue_public_id"`
	RepoOwner         string             `json:"repo_owner"`
	RepoName          string             `json:"repo_name"`
	IssueTitle        string             `json:"issue_title"`
	IssueUrl          string             `json:"issue_url"`
	IssueLanguage     pgtype.Text        `json:"issue_language"`
	IssueDifficulty   pgtype.Text        `json:"issue_difficulty"`
	IssueRepoStars    int32              `json:"issue_repo_stars"`
	IssueLabels       []string           `json:"issue_labels"`
}

func (q *Queries) ListUserDrawsByStatus(ctx context.Context, arg ListUserDrawsByStatusParams) ([]ListUserDrawsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listUserDrawsByStatus, arg.UserID, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserDrawsByStatusRow{}
	for rows.Next() {
		var i ListUserDrawsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.UserID,
			&i.IssueID,
			&i.Status,
			&i.Source,
			&i.PrUrl,
			&i.PrSubmittedAt,
			&i.MergeCommitSha,
			&i.MergedAt,
			&i.ExpiresAt,
			&i.XpAwarded,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrOwnerLogin,
			&i.PrRepoOwner,
			&i.PrRepoName,
			&i.PrNumber,
			&i.PrVerifiedAt,
			&i.RewardProcessedAt,
			&i.RewardSource,
			&i.IssuePublicID,
			&i.RepoOwner,
			&i.RepoName,
			&i.IssueTitle,
			&i.IssueUrl,
			&i.IssueLanguage,
			&i.IssueDifficulty,
			&i.IssueRepoStars,
			&i.IssueLabels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeDraw = `-- name: MergeDraw :one
UPDATE draws
SET
  status = 'merged',
  merged_at = NOW(),
  merge_commit_sha = $2,
  xp_awarded = $3,
  reward_processed_at = NOW(),
  reward_source = $4
WHERE id = $1 AND status = 'pr_submitted' AND reward_processed_at IS NULL
RETURNING id, public_id, user_id, issue_id, status, source, pr_url, pr_submitted_at, merge_commit_sha, merged_at, expires_at, xp_awarded, created_at, updated_at, pr_owner_login, pr_repo_owner, pr_repo_name, pr_number, pr_verified_at, reward_processed_at, reward_source
`

type MergeDrawParams struct {
	ID             int64       `json:"id"`
	MergeCommitSha pgtype.Text `json:"merge_commit_sha"`
	XpAwarded      int32       `json:"xp_awarded"`
	RewardSource   pgtype.Text `json:"reward_source"`
}

func (q *Queries) MergeDraw(ctx context.Context, arg MergeDrawParams) (Draw, error) {
	row := q.db.QueryRow(ctx, mergeDraw,
		arg.ID,
		arg.MergeCommitSha,
		arg.XpAwarded,
		arg.RewardSource,
	)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.IssueID,
		&i.Status,
		&i.Source,
		&i.PrUrl,
		&i.PrSubmittedAt,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ExpiresAt,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrOwnerLogin,
		&i.PrRepoOwner,
		&i.PrRepoName,
		&i.PrNumber,
		&i.PrVerifiedAt,
		&i.RewardProcessedAt,
		&i.RewardSource,
	)
	return i, err
}

const submitPR = `-- name: SubmitPR :one
UPDATE draws
SET
  status = 'pr_submitted',
  pr_url = $2,
  pr_submitted_at = NOW(),
  pr_owner_login = $3,
  pr_repo_owner = $4,
  pr_repo_name = $5,
  pr_number = $6,
  pr_verified_at = NOW()
WHERE id = $1 AND status = 'bookmarked'
RETURNING id, public_id, user_id, issue_id, status, source, pr_url, pr_submitted_at, merge_commit_sha, merged_at, expires_at, xp_awarded, created_at, updated_at, pr_owner_login, pr_repo_owner, pr_repo_name, pr_number, pr_verified_at, reward_processed_at, reward_source
`

type SubmitPRParams struct {
	ID           int64       `json:"id"`
	PrUrl        pgtype.Text `json:"pr_url"`
	PrOwnerLogin pgtype.Text `json:"pr_owner_login"`
	PrRepoOwner  pgtype.Text `json:"pr_repo_owner"`
	PrRepoName   pgtype.Text `json:"pr_repo_name"`
	PrNumber     pgtype.Int4 `json:"pr_number"`
}

func (q *Queries) SubmitPR(ctx context.Context, arg SubmitPRParams) (Draw, error) {
	row := q.db.QueryRow(ctx, submitPR,
		arg.ID,
		arg.PrUrl,
		arg.PrOwnerLogin,
		arg.PrRepoOwner,
		arg.PrRepoName,
		arg.PrNumber,
	)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.IssueID,
		&i.Status,
		&i.Source,
		&i.PrUrl,
		&i.PrSubmittedAt,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ExpiresAt,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrOwnerLogin,
		&i.PrRepoOwner,
		&i.PrRepoName,
		&i.PrNumber,
		&i.PrVerifiedAt,
		&i.RewardProcessedAt,
		&i.RewardSource,
	)
	return i, err
}

const updateDrawStatus = `-- name: UpdateDrawStatus :one
UPDATE draws SET status = $2 WHERE id = $1 AND status = $3 RETURNING id, public_id, user_id, issue_id, status, source, pr_url, pr_submitted_at, merge_commit_sha, merged_at, expires_at, xp_awarded, created_at, updated_at, pr_owner_login, pr_repo_owner, pr_repo_name, pr_number, pr_verified_at, reward_processed_at, reward_source
`

type UpdateDrawStatusParams struct {
	ID            int64      `json:"id"`
	Status        DrawStatus `json:"status"`
	CurrentStatus DrawStatus `json:"current_status"`
}

func (q *Queries) UpdateDrawStatus(ctx context.Context, arg UpdateDrawStatusParams) (Draw, error) {
	row := q.db.QueryRow(ctx, updateDrawStatus, arg.ID, arg.Status, arg.CurrentStatus)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.IssueID,
		&i.Status,
		&i.Source,
		&i.PrUrl,
		&i.PrSubmittedAt,
		&i.MergeCommitSha,
		&i.MergedAt,
		&i.ExpiresAt,
		&i.XpAwarded,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrOwnerLogin,
		&i.PrRepoOwner,
		&i.PrRepoName,
		&i.PrNumber,
		&i.PrVerifiedAt,
		&i.RewardProcessedAt,
		&i.RewardSource,
	)
	return i, err
}
