// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (user_id, event_type, payload) VALUES ($1, $2, $3)
`

type CreateEventParams struct {
	UserID    int64  `json:"user_id"`
	EventType string `json:"event_type"`
	Payload   []byte `json:"payload"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent, arg.UserID, arg.EventType, arg.Payload)
	return err
}

const getUserEvents = `-- name: GetUserEvents :many
SELECT id, user_id, event_type, payload, created_at FROM events WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type GetUserEventsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetUserEvents(ctx context.Context, arg GetUserEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getUserEvents, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
