// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDistinctRepos = `-- name: CountDistinctRepos :one
SELECT COUNT(DISTINCT (repo_owner, repo_name)) FROM issues WHERE state = 'open'
`

func (q *Queries) CountDistinctRepos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDistinctRepos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilteredIssues = `-- name: CountFilteredIssues :one
SELECT COUNT(*) FROM issues
WHERE state = 'open'
  AND ($1::varchar IS NULL OR language = $1)
  AND ($2::varchar IS NULL OR difficulty = $2)
`

type CountFilteredIssuesParams struct {
	Language   pgtype.Text `json:"language"`
	Difficulty pgtype.Text `json:"difficulty"`
}

func (q *Queries) CountFilteredIssues(ctx context.Context, arg CountFilteredIssuesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredIssues, arg.Language, arg.Difficulty)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFilteredIssuesForUser = `-- name: CountFilteredIssuesForUser :one
SELECT COUNT(*) FROM issues
WHERE state = 'open'
  AND ($2::varchar IS NULL OR language = $2)
  AND ($3::varchar IS NULL OR difficulty = $3)
  AND NOT EXISTS (
    SELECT 1 FROM draws d WHERE d.issue_id = issues.id AND d.user_id = $1
  )
`

type CountFilteredIssuesForUserParams struct {
	UserID     int64       `json:"user_id"`
	Language   pgtype.Text `json:"language"`
	Difficulty pgtype.Text `json:"difficulty"`
}

func (q *Queries) CountFilteredIssuesForUser(ctx context.Context, arg CountFilteredIssuesForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredIssuesForUser, arg.UserID, arg.Language, arg.Difficulty)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssues = `-- name: CountIssues :one
SELECT COUNT(*) FROM issues
`

func (q *Queries) CountIssues(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countIssues)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssuesByRarityForUser = `-- name: CountIssuesByRarityForUser :many
SELECT rarity, COUNT(*)::bigint as count FROM issues
WHERE state = 'open'
  AND ($2::varchar IS NULL OR language = $2)
  AND ($3::varchar IS NULL OR difficulty = $3)
  AND NOT EXISTS (
    SELECT 1 FROM draws d WHERE d.issue_id = issues.id AND d.user_id = $1
  )
GROUP BY rarity
`

type CountIssuesByRarityForUserParams struct {
	UserID     int64       `json:"user_id"`
	Language   pgtype.Text `json:"language"`
	Difficulty pgtype.Text `json:"difficulty"`
}

type CountIssuesByRarityForUserRow struct {
	Rarity string `json:"rarity"`
	Count  int64  `json:"count"`
}

// Returns count of available issues per rarity tier for weighted draw selection.
func (q *Queries) CountIssuesByRarityForUser(ctx context.Context, arg CountIssuesByRarityForUserParams) ([]CountIssuesByRarityForUserRow, error) {
	rows, err := q.db.Query(ctx, countIssuesByRarityForUser, arg.UserID, arg.Language, arg.Difficulty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountIssuesByRarityForUserRow{}
	for rows.Next() {
		var i CountIssuesByRarityForUserRow
		if err := rows.Scan(&i.Rarity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenIssues = `-- name: CountOpenIssues :one
SELECT COUNT(*) FROM issues WHERE state = 'open'
`

func (q *Queries) CountOpenIssues(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenIssues)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenIssuesByLanguage = `-- name: CountOpenIssuesByLanguage :many
SELECT language, COUNT(*) as count FROM issues WHERE state = 'open' GROUP BY language ORDER BY count DESC
`

type CountOpenIssuesByLanguageRow struct {
	Language pgtype.Text `json:"language"`
	Count    int64       `json:"count"`
}

func (q *Queries) CountOpenIssuesByLanguage(ctx context.Context) ([]CountOpenIssuesByLanguageRow, error) {
	rows, err := q.db.Query(ctx, countOpenIssuesByLanguage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOpenIssuesByLanguageRow{}
	for rows.Next() {
		var i CountOpenIssuesByLanguageRow
		if err := rows.Scan(&i.Language, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (github_id, github_number, repo_owner, repo_name, title, url, language, difficulty, rarity, repo_stars, repo_pushed_at, github_created_at, labels, state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, public_id, github_id, github_number, repo_owner, repo_name, title, url, language, difficulty, rarity, repo_stars, repo_pushed_at, github_created_at, labels, state, last_synced_at, created_at, updated_at
`

type CreateIssueParams struct {
	GithubID        int64              `json:"github_id"`
	GithubNumber    int32              `json:"github_number"`
	RepoOwner       string             `json:"repo_owner"`
	RepoName        string             `json:"repo_name"`
	Title           string             `json:"title"`
	Url             string             `json:"url"`
	Language        pgtype.Text        `json:"language"`
	Difficulty      pgtype.Text        `json:"difficulty"`
	Rarity          string             `json:"rarity"`
	RepoStars       int32              `json:"repo_stars"`
	RepoPushedAt    pgtype.Timestamptz `json:"repo_pushed_at"`
	GithubCreatedAt pgtype.Timestamptz `json:"github_created_at"`
	Labels          []string           `json:"labels"`
	State           IssueState         `json:"state"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.GithubID,
		arg.GithubNumber,
		arg.RepoOwner,
		arg.RepoName,
		arg.Title,
		arg.Url,
		arg.Language,
		arg.Difficulty,
		arg.Rarity,
		arg.RepoStars,
		arg.RepoPushedAt,
		arg.GithubCreatedAt,
		arg.Labels,
		arg.State,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.GithubID,
		&i.GithubNumber,
		&i.RepoOwner,
		&i.RepoName,
		&i.Title,
		&i.Url,
		&i.Language,
		&i.Difficulty,
		&i.Rarity,
		&i.RepoStars,
		&i.RepoPushedAt,
		&i.GithubCreatedAt,
		&i.Labels,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueByGithubID = `-- name: GetIssueByGithubID :one
SELECT id, public_id, github_id, github_number, repo_owner, repo_name, title, url, language, difficulty, rarity, repo_stars, repo_pushed_at, github_created_at, labels, state, last_synced_at, created_at, updated_at FROM issues WHERE github_id = $1
`

func (q *Queries) GetIssueByGithubID(ctx context.Context, githubID int64) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByGithubID, githubID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.GithubID,
		&i.GithubNumber,
		&i.RepoOwner,
		&i.RepoName,
		&i.Title,
		&i.Url,
		&i.Language,
		&i.Difficulty,
		&i.Rarity,
		&i.RepoStars,
		&i.RepoPushedAt,
		&i.GithubCreatedAt,
		&i.Labels,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, public_id, github_id, github_number, repo_owner, repo_name, title, url, language, difficulty, rarity, repo_stars, repo_pushed_at, github_created_at, labels, state, last_synced_at, created_at, updated_at FROM issues WHERE id = $1
`

func (q *Queries) GetIssueByID(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.GithubID,
		&i.GithubNumber,
		&i.RepoOwner,
		&i.RepoName,
		&i.Title,
		&i.Url,
		&i.Language,
		&i.Difficulty,
		&i.Rarity,
		&i.RepoStars,
		&i.RepoPushedAt,
		&i.GithubCreatedAt,
		&i.Labels,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueByPublicID = `-- name: GetIssueByPublicID :one
SELECT id, public_id, github_id, github_number, repo_owner, repo_name, title, url, language, difficulty, rarity, repo_stars, repo_pushed_at, github_created_at, labels, state, last_synced_at, created_at, updated_at FROM issues WHERE public_id = $1
`

func (q *Queries) GetIssueByPublicID(ctx context.Context, publicID pgtype.UUID) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByPublicID, publicID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.GithubID,
		&i.GithubNumber,
		&i.RepoOwner,
		&i.RepoName,
		&i.Title,
		&i.Url,
		&i.Language,
		&i.Difficulty,
		&i.Rarity,
		&i.RepoStars,
		&i.RepoPushedAt,
		&i.GithubCreatedAt,
		&i.Labels,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRandomIssue = `-- name: GetRandomIssue :one
SELECT id, public_id, github_id, github_number, repo_owner, repo_name, title, url, language, difficulty, rarity, repo_stars, repo_pushed_at, github_created_at, labels, state, last_synced_at, created_at, updated_at FROM issues
WHERE state = 'open'
  AND ($2::varchar IS NULL OR language = $2)
  AND ($3::varchar IS NULL OR difficulty = $3)
OFFSET $1
LIMIT 1
`

type GetRandomIssueParams struct {
	Offset     int32       `json:"offset"`
	Language   pgtype.Text `json:"language"`
	Difficulty pgtype.Text `json:"difficulty"`
}

func (q *Queries) GetRandomIssue(ctx context.Context, arg GetRandomIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, getRandomIssue, arg.Offset, arg.Language, arg.Difficulty)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.GithubID,
		&i.GithubNumber,
		&i.RepoOwner,
		&i.RepoName,
		&i.Title,
		&i.Url,
		&i.Language,
		&i.Difficulty,
		&i.Rarity,
		&i.RepoStars,
		&i.RepoPushedAt,
		&i.GithubCreatedAt,
		&i.Labels,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRandomIssueByRarityForUser = `-- name: GetRandomIssueByRarityForUser :one
SELECT id, public_id, github_id, github_number, repo_owner, repo_name, title, url, language, difficulty, rarity, repo_stars, repo_pushed_at, github_created_at, labels, state, last_synced_at, created_at, updated_at FROM issues
WHERE state = 'open'
  AND rarity = $1
  AND ($4::varchar IS NULL OR language = $4)
  AND ($5::varchar IS NULL OR difficulty = $5)
  AND NOT EXISTS (
    SELECT 1 FROM draws d WHERE d.issue_id = issues.id AND d.user_id = $2
  )
OFFSET $3
LIMIT 1
`

type GetRandomIssueByRarityForUserParams struct {
	Rarity     string      `json:"rarity"`
	UserID     int64       `json:"user_id"`
	Offset     int32       `json:"offset"`
	Language   pgtype.Text `json:"language"`
	Difficulty pgtype.Text `json:"difficulty"`
}

// Picks a random issue of a specific rarity tier, excluding already-drawn issues.
func (q *Queries) GetRandomIssueByRarityForUser(ctx context.Context, arg GetRandomIssueByRarityForUserParams) (Issue, error) {
	row := q.db.QueryRow(ctx, getRandomIssueByRarityForUser,
		arg.Rarity,
		arg.UserID,
		arg.Offset,
		arg.Language,
		arg.Difficulty,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.GithubID,
		&i.GithubNumber,
		&i.RepoOwner,
		&i.RepoName,
		&i.Title,
		&i.Url,
		&i.Language,
		&i.Difficulty,
		&i.Rarity,
		&i.RepoStars,
		&i.RepoPushedAt,
		&i.GithubCreatedAt,
		&i.Labels,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRandomIssueForUser = `-- name: GetRandomIssueForUser :one
SELECT id, public_id, github_id, github_number, repo_owner, repo_name, title, url, language, difficulty, rarity, repo_stars, repo_pushed_at, github_created_at, labels, state, last_synced_at, created_at, updated_at FROM issues
WHERE state = 'open'
  AND ($3::varchar IS NULL OR language = $3)
  AND ($4::varchar IS NULL OR difficulty = $4)
  AND NOT EXISTS (
    SELECT 1 FROM draws d WHERE d.issue_id = issues.id AND d.user_id = $1
  )
OFFSET $2
LIMIT 1
`

type GetRandomIssueForUserParams struct {
	UserID     int64       `json:"user_id"`
	Offset     int32       `json:"offset"`
	Language   pgtype.Text `json:"language"`
	Difficulty pgtype.Text `json:"difficulty"`
}

func (q *Queries) GetRandomIssueForUser(ctx context.Context, arg GetRandomIssueForUserParams) (Issue, error) {
	row := q.db.QueryRow(ctx, getRandomIssueForUser,
		arg.UserID,
		arg.Offset,
		arg.Language,
		arg.Difficulty,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.GithubID,
		&i.GithubNumber,
		&i.RepoOwner,
		&i.RepoName,
		&i.Title,
		&i.Url,
		&i.Language,
		&i.Difficulty,
		&i.Rarity,
		&i.RepoStars,
		&i.RepoPushedAt,
		&i.GithubCreatedAt,
		&i.Labels,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaleIssues = `-- name: GetStaleIssues :many
SELECT id, public_id, github_id, github_number, repo_owner, repo_name, title, url, language, difficulty, rarity, repo_stars, repo_pushed_at, github_created_at, labels, state, last_synced_at, created_at, updated_at FROM issues
WHERE state = 'open'
ORDER BY last_synced_at ASC
LIMIT $1
`

func (q *Queries) GetStaleIssues(ctx context.Context, limit int32) ([]Issue, error) {
	rows, err := q.db.Query(ctx, getStaleIssues, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.GithubID,
			&i.GithubNumber,
			&i.RepoOwner,
			&i.RepoName,
			&i.Title,
			&i.Url,
			&i.Language,
			&i.Difficulty,
			&i.Rarity,
			&i.RepoStars,
			&i.RepoPushedAt,
			&i.GithubCreatedAt,
			&i.Labels,
			&i.State,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssues = `-- name: ListIssues :many
SELECT id, public_id, github_id, github_number, repo_owner, repo_name, title, url, language, difficulty, rarity, repo_stars, repo_pushed_at, github_created_at, labels, state, last_synced_at, created_at, updated_at FROM issues
WHERE state = 'open'
  AND rarity != 'legendary'
  AND ($2::varchar IS NULL OR language = $2)
  AND ($3::varchar IS NULL OR difficulty = $3)
  AND ($4::varchar IS NULL OR rarity = $4)
ORDER BY repo_stars DESC, id DESC
LIMIT $1
`

type ListIssuesParams struct {
	Limit      int32       `json:"limit"`
	Language   pgtype.Text `json:"language"`
	Difficulty pgtype.Text `json:"difficulty"`
	Rarity     pgtype.Text `json:"rarity"`
}

// Browse table: excludes legendary-rarity issues (draw-only).
func (q *Queries) ListIssues(ctx context.Context, arg ListIssuesParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssues,
		arg.Limit,
		arg.Language,
		arg.Difficulty,
		arg.Rarity,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.GithubID,
			&i.GithubNumber,
			&i.RepoOwner,
			&i.RepoName,
			&i.Title,
			&i.Url,
			&i.Language,
			&i.Difficulty,
			&i.Rarity,
			&i.RepoStars,
			&i.RepoPushedAt,
			&i.GithubCreatedAt,
			&i.Labels,
			&i.State,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesAfterCursor = `-- name: ListIssuesAfterCursor :many
SELECT id, public_id, github_id, github_number, repo_owner, repo_name, title, url, language, difficulty, rarity, repo_stars, repo_pushed_at, github_created_at, labels, state, last_synced_at, created_at, updated_at FROM issues
WHERE state = 'open'
  AND rarity != 'legendary'
  AND ($3::varchar IS NULL OR language = $3)
  AND ($4::varchar IS NULL OR difficulty = $4)
  AND ($5::varchar IS NULL OR rarity = $5)
  AND (repo_stars < $1 OR (repo_stars = $1 AND id < $6::bigint))
ORDER BY repo_stars DESC, id DESC
LIMIT $2
`

type ListIssuesAfterCursorParams struct {
	RepoStars  int32       `json:"repo_stars"`
	Limit      int32       `json:"limit"`
	Language   pgtype.Text `json:"language"`
	Difficulty pgtype.Text `json:"difficulty"`
	Rarity     pgtype.Text `json:"rarity"`
	CursorID   int64       `json:"cursor_id"`
}

func (q *Queries) ListIssuesAfterCursor(ctx context.Context, arg ListIssuesAfterCursorParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesAfterCursor,
		arg.RepoStars,
		arg.Limit,
		arg.Language,
		arg.Difficulty,
		arg.Rarity,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.GithubID,
			&i.GithubNumber,
			&i.RepoOwner,
			&i.RepoName,
			&i.Title,
			&i.Url,
			&i.Language,
			&i.Difficulty,
			&i.Rarity,
			&i.RepoStars,
			&i.RepoPushedAt,
			&i.GithubCreatedAt,
			&i.Labels,
			&i.State,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIssueClosed = `-- name: MarkIssueClosed :exec
UPDATE issues SET state = 'closed', last_synced_at = NOW() WHERE id = $1
`

func (q *Queries) MarkIssueClosed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markIssueClosed, id)
	return err
}

const updateIssueSyncedAt = `-- name: UpdateIssueSyncedAt :exec
UPDATE issues SET last_synced_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateIssueSyncedAt(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateIssueSyncedAt, id)
	return err
}

const upsertIssue = `-- name: UpsertIssue :one
INSERT INTO issues (
    github_id, github_number, repo_owner, repo_name, title, url,
    language, difficulty, rarity, repo_stars, repo_pushed_at, github_created_at,
    labels, state, last_synced_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NOW())
ON CONFLICT (github_id) DO UPDATE SET
    title = EXCLUDED.title,
    repo_stars = EXCLUDED.repo_stars,
    labels = EXCLUDED.labels,
    difficulty = EXCLUDED.difficulty,
    rarity = EXCLUDED.rarity,
    repo_pushed_at = EXCLUDED.repo_pushed_at,
    last_synced_at = NOW(),
    state = EXCLUDED.state
RETURNING id, public_id, github_id, github_number, repo_owner, repo_name, title, url, language, difficulty, rarity, repo_stars, repo_pushed_at, github_created_at, labels, state, last_synced_at, created_at, updated_at
`

type UpsertIssueParams struct {
	GithubID        int64              `json:"github_id"`
	GithubNumber    int32              `json:"github_number"`
	RepoOwner       string             `json:"repo_owner"`
	RepoName        string             `json:"repo_name"`
	Title           string             `json:"title"`
	Url             string             `json:"url"`
	Language        pgtype.Text        `json:"language"`
	Difficulty      pgtype.Text        `json:"difficulty"`
	Rarity          string             `json:"rarity"`
	RepoStars       int32              `json:"repo_stars"`
	RepoPushedAt    pgtype.Timestamptz `json:"repo_pushed_at"`
	GithubCreatedAt pgtype.Timestamptz `json:"github_created_at"`
	Labels          []string           `json:"labels"`
	State           IssueState         `json:"state"`
}

func (q *Queries) UpsertIssue(ctx context.Context, arg UpsertIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, upsertIssue,
		arg.GithubID,
		arg.GithubNumber,
		arg.RepoOwner,
		arg.RepoName,
		arg.Title,
		arg.Url,
		arg.Language,
		arg.Difficulty,
		arg.Rarity,
		arg.RepoStars,
		arg.RepoPushedAt,
		arg.GithubCreatedAt,
		arg.Labels,
		arg.State,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.GithubID,
		&i.GithubNumber,
		&i.RepoOwner,
		&i.RepoName,
		&i.Title,
		&i.Url,
		&i.Language,
		&i.Difficulty,
		&i.Rarity,
		&i.RepoStars,
		&i.RepoPushedAt,
		&i.GithubCreatedAt,
		&i.Labels,
		&i.State,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
