// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDistinctRepos = `-- name: CountDistinctRepos :one
SELECT COUNT(DISTINCT (repo_owner, repo_name)) FROM issues WHERE state = 'open'
`

func (q *Queries) CountDistinctRepos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDistinctRepos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssues = `-- name: CountIssues :one
SELECT COUNT(*) FROM issues
`

func (q *Queries) CountIssues(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countIssues)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (github_id, repo_owner, repo_name, title, url, language, difficulty, repo_stars, labels, state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, public_id, github_id, repo_owner, repo_name, title, url, language, difficulty, repo_stars, labels, state, created_at, updated_at
`

type CreateIssueParams struct {
	GithubID   int64       `json:"github_id"`
	RepoOwner  string      `json:"repo_owner"`
	RepoName   string      `json:"repo_name"`
	Title      string      `json:"title"`
	Url        string      `json:"url"`
	Language   pgtype.Text `json:"language"`
	Difficulty pgtype.Text `json:"difficulty"`
	RepoStars  int32       `json:"repo_stars"`
	Labels     []string    `json:"labels"`
	State      IssueState  `json:"state"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.GithubID,
		arg.RepoOwner,
		arg.RepoName,
		arg.Title,
		arg.Url,
		arg.Language,
		arg.Difficulty,
		arg.RepoStars,
		arg.Labels,
		arg.State,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.GithubID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Title,
		&i.Url,
		&i.Language,
		&i.Difficulty,
		&i.RepoStars,
		&i.Labels,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, public_id, github_id, repo_owner, repo_name, title, url, language, difficulty, repo_stars, labels, state, created_at, updated_at FROM issues WHERE id = $1
`

func (q *Queries) GetIssueByID(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.GithubID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Title,
		&i.Url,
		&i.Language,
		&i.Difficulty,
		&i.RepoStars,
		&i.Labels,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueByPublicID = `-- name: GetIssueByPublicID :one
SELECT id, public_id, github_id, repo_owner, repo_name, title, url, language, difficulty, repo_stars, labels, state, created_at, updated_at FROM issues WHERE public_id = $1
`

func (q *Queries) GetIssueByPublicID(ctx context.Context, publicID pgtype.UUID) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByPublicID, publicID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.GithubID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Title,
		&i.Url,
		&i.Language,
		&i.Difficulty,
		&i.RepoStars,
		&i.Labels,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRandomIssue = `-- name: GetRandomIssue :one
SELECT id, public_id, github_id, repo_owner, repo_name, title, url, language, difficulty, repo_stars, labels, state, created_at, updated_at FROM issues
WHERE state = 'open'
  AND ($1::varchar IS NULL OR language = $1)
  AND ($2::varchar IS NULL OR difficulty = $2)
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomIssueParams struct {
	Language   pgtype.Text `json:"language"`
	Difficulty pgtype.Text `json:"difficulty"`
}

func (q *Queries) GetRandomIssue(ctx context.Context, arg GetRandomIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, getRandomIssue, arg.Language, arg.Difficulty)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.GithubID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Title,
		&i.Url,
		&i.Language,
		&i.Difficulty,
		&i.RepoStars,
		&i.Labels,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIssues = `-- name: ListIssues :many
SELECT id, public_id, github_id, repo_owner, repo_name, title, url, language, difficulty, repo_stars, labels, state, created_at, updated_at FROM issues
WHERE state = 'open'
  AND ($2::varchar IS NULL OR language = $2)
  AND ($3::varchar IS NULL OR difficulty = $3)
ORDER BY repo_stars DESC
LIMIT $1
`

type ListIssuesParams struct {
	Limit      int32       `json:"limit"`
	Language   pgtype.Text `json:"language"`
	Difficulty pgtype.Text `json:"difficulty"`
}

func (q *Queries) ListIssues(ctx context.Context, arg ListIssuesParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssues, arg.Limit, arg.Language, arg.Difficulty)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.GithubID,
			&i.RepoOwner,
			&i.RepoName,
			&i.Title,
			&i.Url,
			&i.Language,
			&i.Difficulty,
			&i.RepoStars,
			&i.Labels,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesAfterCursor = `-- name: ListIssuesAfterCursor :many
SELECT id, public_id, github_id, repo_owner, repo_name, title, url, language, difficulty, repo_stars, labels, state, created_at, updated_at FROM issues
WHERE state = 'open'
  AND ($4::varchar IS NULL OR language = $4)
  AND ($5::varchar IS NULL OR difficulty = $5)
  AND (repo_stars, id) < ($1, $2)
ORDER BY repo_stars DESC, id DESC
LIMIT $3
`

type ListIssuesAfterCursorParams struct {
	RepoStars   int32       `json:"repo_stars"`
	RepoStars_2 int32       `json:"repo_stars_2"`
	Limit       int32       `json:"limit"`
	Language    pgtype.Text `json:"language"`
	Difficulty  pgtype.Text `json:"difficulty"`
}

func (q *Queries) ListIssuesAfterCursor(ctx context.Context, arg ListIssuesAfterCursorParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesAfterCursor,
		arg.RepoStars,
		arg.RepoStars_2,
		arg.Limit,
		arg.Language,
		arg.Difficulty,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.GithubID,
			&i.RepoOwner,
			&i.RepoName,
			&i.Title,
			&i.Url,
			&i.Language,
			&i.Difficulty,
			&i.RepoStars,
			&i.Labels,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
