// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityAction string

const (
	ActivityActionMerged          ActivityAction = "merged"
	ActivityActionBadgeEarned     ActivityAction = "badge_earned"
	ActivityActionStreakMilestone ActivityAction = "streak_milestone"
)

func (e *ActivityAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityAction(s)
	case string:
		*e = ActivityAction(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityAction: %T", src)
	}
	return nil
}

type NullActivityAction struct {
	ActivityAction ActivityAction `json:"activity_action"`
	Valid          bool           `json:"valid"` // Valid is true if ActivityAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityAction) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityAction), nil
}

type DrawStatus string

const (
	DrawStatusDrawn       DrawStatus = "drawn"
	DrawStatusBookmarked  DrawStatus = "bookmarked"
	DrawStatusExpired     DrawStatus = "expired"
	DrawStatusPrSubmitted DrawStatus = "pr_submitted"
	DrawStatusMerged      DrawStatus = "merged"
	DrawStatusAbandoned   DrawStatus = "abandoned"
)

func (e *DrawStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DrawStatus(s)
	case string:
		*e = DrawStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DrawStatus: %T", src)
	}
	return nil
}

type NullDrawStatus struct {
	DrawStatus DrawStatus `json:"draw_status"`
	Valid      bool       `json:"valid"` // Valid is true if DrawStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDrawStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DrawStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DrawStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDrawStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DrawStatus), nil
}

type IssueState string

const (
	IssueStateOpen   IssueState = "open"
	IssueStateClosed IssueState = "closed"
	IssueStateStale  IssueState = "stale"
)

func (e *IssueState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueState(s)
	case string:
		*e = IssueState(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueState: %T", src)
	}
	return nil
}

type NullIssueState struct {
	IssueState IssueState `json:"issue_state"`
	Valid      bool       `json:"valid"` // Valid is true if IssueState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueState) Scan(value interface{}) error {
	if value == nil {
		ns.IssueState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueState), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusDeleted   UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Activity struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	DrawID    pgtype.Int8        `json:"draw_id"`
	Action    ActivityAction     `json:"action"`
	RepoOwner pgtype.Text        `json:"repo_owner"`
	RepoName  pgtype.Text        `json:"repo_name"`
	Title     pgtype.Text        `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Badge struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
}

type Draw struct {
	ID             int64              `json:"id"`
	PublicID       pgtype.UUID        `json:"public_id"`
	UserID         int64              `json:"user_id"`
	IssueID        int64              `json:"issue_id"`
	Status         DrawStatus         `json:"status"`
	Source         string             `json:"source"`
	PrUrl          pgtype.Text        `json:"pr_url"`
	PrSubmittedAt  pgtype.Timestamptz `json:"pr_submitted_at"`
	MergeCommitSha pgtype.Text        `json:"merge_commit_sha"`
	MergedAt       pgtype.Timestamptz `json:"merged_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	XpAwarded      int32              `json:"xp_awarded"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	EventType string             `json:"event_type"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Issue struct {
	ID         int64              `json:"id"`
	PublicID   pgtype.UUID        `json:"public_id"`
	GithubID   int64              `json:"github_id"`
	RepoOwner  string             `json:"repo_owner"`
	RepoName   string             `json:"repo_name"`
	Title      string             `json:"title"`
	Url        string             `json:"url"`
	Language   pgtype.Text        `json:"language"`
	Difficulty pgtype.Text        `json:"difficulty"`
	RepoStars  int32              `json:"repo_stars"`
	Labels     []string           `json:"labels"`
	State      IssueState         `json:"state"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                   int64              `json:"id"`
	PublicID             pgtype.UUID        `json:"public_id"`
	FirebaseUid          string             `json:"firebase_uid"`
	Username             string             `json:"username"`
	Email                string             `json:"email"`
	DisplayName          string             `json:"display_name"`
	AvatarUrl            string             `json:"avatar_url"`
	GithubID             pgtype.Text        `json:"github_id"`
	GithubUsername       pgtype.Text        `json:"github_username"`
	Xp                   int32              `json:"xp"`
	Level                int32              `json:"level"`
	CurrentStreak        int32              `json:"current_streak"`
	LongestStreak        int32              `json:"longest_streak"`
	LastContributionDate pgtype.Timestamptz `json:"last_contribution_date"`
	TotalContributions   int32              `json:"total_contributions"`
	Filters              []byte             `json:"filters"`
	Status               UserStatus         `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type UserBadge struct {
	ID       int64              `json:"id"`
	UserID   int64              `json:"user_id"`
	BadgeID  int64              `json:"badge_id"`
	DrawID   pgtype.Int8        `json:"draw_id"`
	EarnedAt pgtype.Timestamptz `json:"earned_at"`
}
