// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) FROM users WHERE status = 'active'
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (firebase_uid, username, email, display_name, avatar_url, github_id, github_username)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, public_id, firebase_uid, username, email, display_name, avatar_url, github_id, github_username, xp, level, current_streak, longest_streak, last_contribution_date, total_contributions, filters, status, created_at, updated_at, daily_draw_limit
`

type CreateUserParams struct {
	FirebaseUid    string      `json:"firebase_uid"`
	Username       string      `json:"username"`
	Email          string      `json:"email"`
	DisplayName    string      `json:"display_name"`
	AvatarUrl      string      `json:"avatar_url"`
	GithubID       pgtype.Text `json:"github_id"`
	GithubUsername pgtype.Text `json:"github_username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirebaseUid,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.GithubID,
		arg.GithubUsername,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FirebaseUid,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GithubID,
		&i.GithubUsername,
		&i.Xp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastContributionDate,
		&i.TotalContributions,
		&i.Filters,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailyDrawLimit,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT id, public_id, username, display_name, avatar_url, xp, level, total_contributions
FROM users
WHERE status = 'active'
ORDER BY xp DESC, id DESC
LIMIT $1
`

type GetLeaderboardRow struct {
	ID                 int64       `json:"id"`
	PublicID           pgtype.UUID `json:"public_id"`
	Username           string      `json:"username"`
	DisplayName        string      `json:"display_name"`
	AvatarUrl          string      `json:"avatar_url"`
	Xp                 int32       `json:"xp"`
	Level              int32       `json:"level"`
	TotalContributions int32       `json:"total_contributions"`
}

func (q *Queries) GetLeaderboard(ctx context.Context, limit int32) ([]GetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeaderboardRow{}
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Xp,
			&i.Level,
			&i.TotalContributions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardAfterCursor = `-- name: GetLeaderboardAfterCursor :many
SELECT id, public_id, username, display_name, avatar_url, xp, level, total_contributions
FROM users
WHERE status = 'active' AND (xp < $1 OR (xp = $1 AND id < $3::bigint))
ORDER BY xp DESC, id DESC
LIMIT $2
`

type GetLeaderboardAfterCursorParams struct {
	Xp       int32 `json:"xp"`
	Limit    int32 `json:"limit"`
	CursorID int64 `json:"cursor_id"`
}

type GetLeaderboardAfterCursorRow struct {
	ID                 int64       `json:"id"`
	PublicID           pgtype.UUID `json:"public_id"`
	Username           string      `json:"username"`
	DisplayName        string      `json:"display_name"`
	AvatarUrl          string      `json:"avatar_url"`
	Xp                 int32       `json:"xp"`
	Level              int32       `json:"level"`
	TotalContributions int32       `json:"total_contributions"`
}

func (q *Queries) GetLeaderboardAfterCursor(ctx context.Context, arg GetLeaderboardAfterCursorParams) ([]GetLeaderboardAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboardAfterCursor, arg.Xp, arg.Limit, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeaderboardAfterCursorRow{}
	for rows.Next() {
		var i GetLeaderboardAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Xp,
			&i.Level,
			&i.TotalContributions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, public_id, firebase_uid, username, email, display_name, avatar_url, github_id, github_username, xp, level, current_streak, longest_streak, last_contribution_date, total_contributions, filters, status, created_at, updated_at, daily_draw_limit FROM users WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FirebaseUid,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GithubID,
		&i.GithubUsername,
		&i.Xp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastContributionDate,
		&i.TotalContributions,
		&i.Filters,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailyDrawLimit,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, firebase_uid, username, email, display_name, avatar_url, github_id, github_username, xp, level, current_streak, longest_streak, last_contribution_date, total_contributions, filters, status, created_at, updated_at, daily_draw_limit FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FirebaseUid,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GithubID,
		&i.GithubUsername,
		&i.Xp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastContributionDate,
		&i.TotalContributions,
		&i.Filters,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailyDrawLimit,
	)
	return i, err
}

const getUserByPublicID = `-- name: GetUserByPublicID :one
SELECT id, public_id, firebase_uid, username, email, display_name, avatar_url, github_id, github_username, xp, level, current_streak, longest_streak, last_contribution_date, total_contributions, filters, status, created_at, updated_at, daily_draw_limit FROM users WHERE public_id = $1
`

func (q *Queries) GetUserByPublicID(ctx context.Context, publicID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPublicID, publicID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FirebaseUid,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GithubID,
		&i.GithubUsername,
		&i.Xp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastContributionDate,
		&i.TotalContributions,
		&i.Filters,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailyDrawLimit,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, public_id, firebase_uid, username, email, display_name, avatar_url, github_id, github_username, xp, level, current_streak, longest_streak, last_contribution_date, total_contributions, filters, status, created_at, updated_at, daily_draw_limit FROM users WHERE LOWER(username) = LOWER($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FirebaseUid,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GithubID,
		&i.GithubUsername,
		&i.Xp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastContributionDate,
		&i.TotalContributions,
		&i.Filters,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailyDrawLimit,
	)
	return i, err
}

const incrementContributions = `-- name: IncrementContributions :exec
UPDATE users SET total_contributions = total_contributions + 1 WHERE id = $1
`

func (q *Queries) IncrementContributions(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementContributions, id)
	return err
}

const syncUserFromFirebase = `-- name: SyncUserFromFirebase :one
UPDATE users SET email = $2, display_name = $3, avatar_url = $4 WHERE firebase_uid = $1 RETURNING id, public_id, firebase_uid, username, email, display_name, avatar_url, github_id, github_username, xp, level, current_streak, longest_streak, last_contribution_date, total_contributions, filters, status, created_at, updated_at, daily_draw_limit
`

type SyncUserFromFirebaseParams struct {
	FirebaseUid string `json:"firebase_uid"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	AvatarUrl   string `json:"avatar_url"`
}

func (q *Queries) SyncUserFromFirebase(ctx context.Context, arg SyncUserFromFirebaseParams) (User, error) {
	row := q.db.QueryRow(ctx, syncUserFromFirebase,
		arg.FirebaseUid,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FirebaseUid,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GithubID,
		&i.GithubUsername,
		&i.Xp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastContributionDate,
		&i.TotalContributions,
		&i.Filters,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailyDrawLimit,
	)
	return i, err
}

const updateUserDailyDrawLimitByUsername = `-- name: UpdateUserDailyDrawLimitByUsername :one
UPDATE users SET daily_draw_limit = $2 WHERE LOWER(username) = LOWER($1) RETURNING id, public_id, firebase_uid, username, email, display_name, avatar_url, github_id, github_username, xp, level, current_streak, longest_streak, last_contribution_date, total_contributions, filters, status, created_at, updated_at, daily_draw_limit
`

type UpdateUserDailyDrawLimitByUsernameParams struct {
	Lower          string      `json:"lower"`
	DailyDrawLimit pgtype.Int4 `json:"daily_draw_limit"`
}

func (q *Queries) UpdateUserDailyDrawLimitByUsername(ctx context.Context, arg UpdateUserDailyDrawLimitByUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserDailyDrawLimitByUsername, arg.Lower, arg.DailyDrawLimit)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FirebaseUid,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GithubID,
		&i.GithubUsername,
		&i.Xp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastContributionDate,
		&i.TotalContributions,
		&i.Filters,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailyDrawLimit,
	)
	return i, err
}

const updateUserFilters = `-- name: UpdateUserFilters :one
UPDATE users SET filters = $2 WHERE id = $1 RETURNING id, public_id, firebase_uid, username, email, display_name, avatar_url, github_id, github_username, xp, level, current_streak, longest_streak, last_contribution_date, total_contributions, filters, status, created_at, updated_at, daily_draw_limit
`

type UpdateUserFiltersParams struct {
	ID      int64  `json:"id"`
	Filters []byte `json:"filters"`
}

func (q *Queries) UpdateUserFilters(ctx context.Context, arg UpdateUserFiltersParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserFilters, arg.ID, arg.Filters)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FirebaseUid,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GithubID,
		&i.GithubUsername,
		&i.Xp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastContributionDate,
		&i.TotalContributions,
		&i.Filters,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailyDrawLimit,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET display_name = $2, avatar_url = $3 WHERE id = $1 RETURNING id, public_id, firebase_uid, username, email, display_name, avatar_url, github_id, github_username, xp, level, current_streak, longest_streak, last_contribution_date, total_contributions, filters, status, created_at, updated_at, daily_draw_limit
`

type UpdateUserProfileParams struct {
	ID          int64  `json:"id"`
	DisplayName string `json:"display_name"`
	AvatarUrl   string `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FirebaseUid,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GithubID,
		&i.GithubUsername,
		&i.Xp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastContributionDate,
		&i.TotalContributions,
		&i.Filters,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailyDrawLimit,
	)
	return i, err
}

const updateUserStreak = `-- name: UpdateUserStreak :exec
UPDATE users SET current_streak = $2, longest_streak = $3, last_contribution_date = $4 WHERE id = $1
`

type UpdateUserStreakParams struct {
	ID                   int64              `json:"id"`
	CurrentStreak        int32              `json:"current_streak"`
	LongestStreak        int32              `json:"longest_streak"`
	LastContributionDate pgtype.Timestamptz `json:"last_contribution_date"`
}

func (q *Queries) UpdateUserStreak(ctx context.Context, arg UpdateUserStreakParams) error {
	_, err := q.db.Exec(ctx, updateUserStreak,
		arg.ID,
		arg.CurrentStreak,
		arg.LongestStreak,
		arg.LastContributionDate,
	)
	return err
}

const updateUserXP = `-- name: UpdateUserXP :one
UPDATE users SET xp = $2, level = $3 WHERE id = $1 RETURNING id, public_id, firebase_uid, username, email, display_name, avatar_url, github_id, github_username, xp, level, current_streak, longest_streak, last_contribution_date, total_contributions, filters, status, created_at, updated_at, daily_draw_limit
`

type UpdateUserXPParams struct {
	ID    int64 `json:"id"`
	Xp    int32 `json:"xp"`
	Level int32 `json:"level"`
}

func (q *Queries) UpdateUserXP(ctx context.Context, arg UpdateUserXPParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserXP, arg.ID, arg.Xp, arg.Level)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.FirebaseUid,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.GithubID,
		&i.GithubUsername,
		&i.Xp,
		&i.Level,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastContributionDate,
		&i.TotalContributions,
		&i.Filters,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DailyDrawLimit,
	)
	return i, err
}
