#!/usr/bin/env bash
set -euo pipefail

# deploy.sh — Called by GitHub Actions (self-hosted runner on VPS)
# Usage: ./deploy.sh <environment> <image_tag>
# Example: ./deploy.sh prod prod-abc1234
#
# The script uses two directories:
#   REPO_DIR  — the Git checkout (compose files, caddy config, migrations)
#   VPS_DIR   — persistent VPS directory (env files, Docker secrets)
#
# When run by the self-hosted runner, REPO_DIR is the runner's work directory
# (detected via GITHUB_WORKSPACE). VPS_DIR defaults to ~/gitfable.
#
# Required env vars (from GitHub Actions secrets):
#   GHCR_TOKEN, GHCR_USERNAME          — GHCR authentication
#   POSTGRES_USER, POSTGRES_PASSWORD    — Database credentials
#   REDIS_PASSWORD                      — Redis password
#   SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY — Supabase auth
#   APP_GITHUB_TOKEN                    — GitHub API token for issue sync
#   GITHUB_WEBHOOK_SECRET               — Webhook signature verification (optional)

ENV="${1:?Usage: deploy.sh <prod|dev> <image_tag>}"
IMAGE_TAG="${2:?Usage: deploy.sh <prod|dev> <image_tag>}"

if [[ "$ENV" != "prod" && "$ENV" != "dev" ]]; then
    echo "ERROR: Environment must be 'prod' or 'dev', got: $ENV"
    exit 1
fi

: "${GHCR_TOKEN:?ERROR: GHCR_TOKEN environment variable is required}"
: "${GHCR_USERNAME:?ERROR: GHCR_USERNAME environment variable is required}"
: "${POSTGRES_USER:?ERROR: POSTGRES_USER environment variable is required}"
: "${POSTGRES_PASSWORD:?ERROR: POSTGRES_PASSWORD environment variable is required}"
: "${REDIS_PASSWORD:?ERROR: REDIS_PASSWORD environment variable is required}"
: "${SUPABASE_URL:?ERROR: SUPABASE_URL environment variable is required}"
: "${SUPABASE_SERVICE_ROLE_KEY:?ERROR: SUPABASE_SERVICE_ROLE_KEY environment variable is required}"
: "${APP_GITHUB_TOKEN:?ERROR: APP_GITHUB_TOKEN environment variable is required}"

# Repo files come from the checkout; VPS-specific files from the persistent directory
REPO_DIR="${GITHUB_WORKSPACE:-$HOME/gitfable}"
VPS_DIR="${VPS_DIR:-$HOME/gitfable}"

COMPOSE_FILE="$REPO_DIR/docker/docker-compose.vps-${ENV}.yml"
# Secrets and env file go in the checkout's docker/ dir so Docker can bind-mount them
# (Docker doesn't follow symlinks for bind mounts)
ENV_FILE="$REPO_DIR/docker/.env.vps-${ENV}"
SECRETS_DIR="$REPO_DIR/docker/secrets"

if [ ! -f "$COMPOSE_FILE" ]; then
    echo "ERROR: Compose file not found: $COMPOSE_FILE"
    exit 1
fi

echo "=== Deploying GitFable ($ENV) with tag: $IMAGE_TAG ==="
echo "Repo dir: $REPO_DIR"
echo "VPS dir:  $VPS_DIR"

# --- Auto-provision VPS directory structure ---
echo "Provisioning VPS config files..."
mkdir -p "$SECRETS_DIR"

# Write Docker secret files
echo -n "$POSTGRES_USER" > "$SECRETS_DIR/postgres_user.txt"
echo -n "$POSTGRES_PASSWORD" > "$SECRETS_DIR/postgres_password.txt"
echo -n "$REDIS_PASSWORD" > "$SECRETS_DIR/redis_password.txt"
chmod 600 "$SECRETS_DIR"/*.txt

# Generate env file from secrets
if [ "$ENV" = "prod" ]; then
    DB_NAME="gitfable_prod"
    DB_POOL_SIZE=25
    CORS_DOMAIN="https://gitfable.app"
    ENVIRONMENT="production"
else
    DB_NAME="gitfable_dev"
    DB_POOL_SIZE=10
    CORS_DOMAIN="https://dev.gitfable.app"
    ENVIRONMENT="development"
fi

cat > "$ENV_FILE" <<ENVEOF
# Auto-generated by deploy.sh — do not edit manually
ENVIRONMENT=${ENVIRONMENT}
PORT=8001
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
DB_POOL_SIZE=${DB_POOL_SIZE}
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
CORS_ORIGINS=${CORS_DOMAIN}
FRONTEND_URL=${CORS_DOMAIN}
GITHUB_TOKEN=${APP_GITHUB_TOKEN}
GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET:-}
RATE_LIMIT_ENABLED=true
SYNC_ENABLED=true
SYNC_INTERVAL=6h
STALE_INTERVAL=12h
ENVEOF
chmod 600 "$ENV_FILE"

# Login to GHCR
echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin

# Set the image tag for this deploy
export IMAGE_TAG="$IMAGE_TAG"

# Pull new images
echo "Pulling images..."
docker compose -f "$COMPOSE_FILE" pull backend frontend

# Deploy with zero-downtime (recreate only changed services)
echo "Starting services..."
docker compose -f "$COMPOSE_FILE" up -d --remove-orphans

# Wait for backend to be healthy
echo "Waiting for backend health check..."
RETRIES=30
until docker inspect --format='{{.State.Health.Status}}' "gitfable-backend-${ENV}" 2>/dev/null | grep -q "healthy"; do
    RETRIES=$((RETRIES - 1))
    if [ $RETRIES -le 0 ]; then
        echo "ERROR: Backend failed health check after 60s"
        echo "Logs:"
        docker compose -f "$COMPOSE_FILE" logs --tail 50 backend
        exit 1
    fi
    sleep 2
done

echo "Backend healthy!"

# Run database migrations.
# In production, migrations do NOT run on startup (only in dev). Run them explicitly here.
echo "Running database migrations..."
NETWORK="gitfable-${ENV}_gitfable-network"

docker run --rm \
  --network "$NETWORK" \
  -v "$REPO_DIR/backend/sql/migrations:/migrations" \
  migrate/migrate \
  -path=/migrations \
  -database="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@gitfable-postgres-${ENV}:5432/${DB_NAME}?sslmode=disable" \
  up

echo "Migrations complete!"

echo "=== Deploy complete ($ENV) ==="
docker compose -f "$COMPOSE_FILE" ps
